version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Breaking_Bread_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - breaking_bread_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - breaking_bread_network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=Breaking_Bread_development
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
    env_file:
      - .env
    networks:
      - breaking_bread_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  bundle_cache:

networks:
  breaking_bread_network:
    driver: bridge
