services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: Breaking_Bread_production
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 4000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_NAME=Breaking_Bread_production
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

